# Generated by Django 4.0.2 on 2022-02-14 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('department_description', models.CharField(max_length=55)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('role_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_description', models.CharField(max_length=60)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.role')),
            ],
        ),
    ]
